version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      hotchocolate-deps:
        patterns:
          - "HotChocolate.*"
        update-types:
        - "minor"
        - "patch"
      fluentValidation-deps:
        patterns:
          - "FluentValidation*"
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular-deps:
        patterns:
          - "@angular/*"
          - "@angular-devkit/build-angular"
          - "@schematics/angular"
        update-types:
        - "minor"
        - "patch"
      eslint-deps:
        patterns:
          - "@angular-eslint/*"
        update-types:
        - "minor"
        - "patch"
      react-deps:
        patterns:
          - "react*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      nx-deps:
        patterns:
          - "@nx/*"
        update-types:
          - "minor"
          - "patch"
      storybook-deps:
        patterns:
          - "@storybook/*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 12
