name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["hard-rox/1"]
assignees: ["hard-rox"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      value: |
        1. Step 1
        2. Step 2
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Docker**: 24.0.7
          - **kathanika**: latest
      value: |
          - OS:
          - Docker:
          - kathanika:
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
