name: Feature Request
description: File a feature request
title: "[Feat]: "
labels: ["feature"]
projects: ["hard-rox/1"]
assignees: ["hard-rox"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      value: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: fields
    attributes:
      label: Fields to be collected
      value: |
        - Field 1
        - Field 2
        - Field 3
      render: Markdown
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] Task 1 done
        - [ ] Task 2 done
        - [ ] Task 3 done
        - [ ] ...
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are proposing!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false