# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Installing Packages
      run: npm ci

    - uses: nrwl/nx-set-shas@v3
    # This line is needed for nx affected to work when CI is running on a PR
    - name: Branch Tracking for NX affected
      run: git branch --track main origin/main
      
    - name: Lint
      run: npx nx affected -t lint

    - name: Build
      run: npx nx affected -t build

    - name: Test
      run: npx nx affected -t test
